#!/bin/bash

# Install Terraform if not already installed
if ! [ -x "$(command -v terraform)" ]; then
  echo "Terraform not found! Installing..."
  wget https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
  unzip terraform_1.5.6_linux_amd64.zip
  mv terraform /usr/local/bin/
  terraform --version
fi

# Navigate to the workspace directory
cd $WORKSPACE

# Initialize Terraform
terraform init

# Format Terraform files
terraform fmt

# Validate Terraform configuration
terraform validate

# Apply Terraform configuration (auto-approve)
terraform apply --auto-approve
